<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-GFANGBB" failures="1" tests="2" name="Error Validations Test" time="15.364" errors="0" timestamp="2025-03-20T01:51:05 CDT">
  <testcase classname="drapercompany.tests.ErrorValidationsTest" name="loginErrorValidation" time="1.205"/>
  <testcase classname="drapercompany.tests.ErrorValidationsTest" name="productErrorValidation" time="2.758">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at drapercompany.tests.ErrorValidationsTest.productErrorValidation(ErrorValidationsTest.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- productErrorValidation -->
</testsuite> <!-- Error Validations Test -->
